// THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
// BY HAND!!
//
// Generated by lcm-gen

#include <string.h>
#include "FOC_motor_t.h"

static int __FOC_motor_t_hash_computed;
static uint64_t __FOC_motor_t_hash;

uint64_t __FOC_motor_t_hash_recursive(const __lcm_hash_ptr *p)
{
    const __lcm_hash_ptr *fp;
    for (fp = p; fp != NULL; fp = fp->parent)
        if (fp->v == __FOC_motor_t_get_hash)
            return 0;

    __lcm_hash_ptr cp;
    cp.parent =  p;
    cp.v = __FOC_motor_t_get_hash;
    (void) cp;

    uint64_t hash = (uint64_t)0xda042e0da5c652d5LL
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __int8_t_hash_recursive(&cp)
         + __int8_t_hash_recursive(&cp)
         + __int8_t_hash_recursive(&cp)
         + __int8_t_hash_recursive(&cp)
        ;

    return (hash<<1) + ((hash>>63)&1);
}

int64_t __FOC_motor_t_get_hash(void)
{
    if (!__FOC_motor_t_hash_computed) {
        __FOC_motor_t_hash = (int64_t)__FOC_motor_t_hash_recursive(NULL);
        __FOC_motor_t_hash_computed = 1;
    }

    return __FOC_motor_t_hash;
}

int __FOC_motor_t_encode_array(void *buf, int offset, int maxlen, const FOC_motor_t *p, int elements)
{
    int pos = 0, element;
    int thislen;

    for (element = 0; element < elements; element++) {

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &(p[element].position), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &(p[element].position_cmd), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &(p[element].velocity), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &(p[element].velocity_cmd), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &(p[element].torque), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &(p[element].torque_cmd), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &(p[element].iq), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &(p[element].iq_cmd), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &(p[element].id), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &(p[element].vq), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &(p[element].vq_cmd), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &(p[element].vd), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &(p[element].kp), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &(p[element].kd), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int8_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].led), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int8_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].cmd_id), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int8_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].flag), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int8_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].control_flag), 1);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int FOC_motor_t_encode(void *buf, int offset, int maxlen, const FOC_motor_t *p)
{
    int pos = 0, thislen;
    int64_t hash = __FOC_motor_t_get_hash();

    thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    thislen = __FOC_motor_t_encode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int __FOC_motor_t_encoded_array_size(const FOC_motor_t *p, int elements)
{
    int size = 0, element;
    for (element = 0; element < elements; element++) {

        size += __double_encoded_array_size(&(p[element].position), 1);

        size += __double_encoded_array_size(&(p[element].position_cmd), 1);

        size += __double_encoded_array_size(&(p[element].velocity), 1);

        size += __double_encoded_array_size(&(p[element].velocity_cmd), 1);

        size += __double_encoded_array_size(&(p[element].torque), 1);

        size += __double_encoded_array_size(&(p[element].torque_cmd), 1);

        size += __double_encoded_array_size(&(p[element].iq), 1);

        size += __double_encoded_array_size(&(p[element].iq_cmd), 1);

        size += __double_encoded_array_size(&(p[element].id), 1);

        size += __double_encoded_array_size(&(p[element].vq), 1);

        size += __double_encoded_array_size(&(p[element].vq_cmd), 1);

        size += __double_encoded_array_size(&(p[element].vd), 1);

        size += __double_encoded_array_size(&(p[element].kp), 1);

        size += __double_encoded_array_size(&(p[element].kd), 1);

        size += __int8_t_encoded_array_size(&(p[element].led), 1);

        size += __int8_t_encoded_array_size(&(p[element].cmd_id), 1);

        size += __int8_t_encoded_array_size(&(p[element].flag), 1);

        size += __int8_t_encoded_array_size(&(p[element].control_flag), 1);

    }
    return size;
}

int FOC_motor_t_encoded_size(const FOC_motor_t *p)
{
    return 8 + __FOC_motor_t_encoded_array_size(p, 1);
}

int __FOC_motor_t_decode_array(const void *buf, int offset, int maxlen, FOC_motor_t *p, int elements)
{
    int pos = 0, thislen, element;

    for (element = 0; element < elements; element++) {

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &(p[element].position), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &(p[element].position_cmd), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &(p[element].velocity), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &(p[element].velocity_cmd), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &(p[element].torque), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &(p[element].torque_cmd), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &(p[element].iq), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &(p[element].iq_cmd), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &(p[element].id), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &(p[element].vq), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &(p[element].vq_cmd), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &(p[element].vd), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &(p[element].kp), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &(p[element].kd), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int8_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].led), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int8_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].cmd_id), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int8_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].flag), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int8_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].control_flag), 1);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int __FOC_motor_t_decode_array_cleanup(FOC_motor_t *p, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __double_decode_array_cleanup(&(p[element].position), 1);

        __double_decode_array_cleanup(&(p[element].position_cmd), 1);

        __double_decode_array_cleanup(&(p[element].velocity), 1);

        __double_decode_array_cleanup(&(p[element].velocity_cmd), 1);

        __double_decode_array_cleanup(&(p[element].torque), 1);

        __double_decode_array_cleanup(&(p[element].torque_cmd), 1);

        __double_decode_array_cleanup(&(p[element].iq), 1);

        __double_decode_array_cleanup(&(p[element].iq_cmd), 1);

        __double_decode_array_cleanup(&(p[element].id), 1);

        __double_decode_array_cleanup(&(p[element].vq), 1);

        __double_decode_array_cleanup(&(p[element].vq_cmd), 1);

        __double_decode_array_cleanup(&(p[element].vd), 1);

        __double_decode_array_cleanup(&(p[element].kp), 1);

        __double_decode_array_cleanup(&(p[element].kd), 1);

        __int8_t_decode_array_cleanup(&(p[element].led), 1);

        __int8_t_decode_array_cleanup(&(p[element].cmd_id), 1);

        __int8_t_decode_array_cleanup(&(p[element].flag), 1);

        __int8_t_decode_array_cleanup(&(p[element].control_flag), 1);

    }
    return 0;
}

int FOC_motor_t_decode(const void *buf, int offset, int maxlen, FOC_motor_t *p)
{
    int pos = 0, thislen;
    int64_t hash = __FOC_motor_t_get_hash();

    int64_t this_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (this_hash != hash) return -1;

    thislen = __FOC_motor_t_decode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int FOC_motor_t_decode_cleanup(FOC_motor_t *p)
{
    return __FOC_motor_t_decode_array_cleanup(p, 1);
}

int __FOC_motor_t_clone_array(const FOC_motor_t *p, FOC_motor_t *q, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __double_clone_array(&(p[element].position), &(q[element].position), 1);

        __double_clone_array(&(p[element].position_cmd), &(q[element].position_cmd), 1);

        __double_clone_array(&(p[element].velocity), &(q[element].velocity), 1);

        __double_clone_array(&(p[element].velocity_cmd), &(q[element].velocity_cmd), 1);

        __double_clone_array(&(p[element].torque), &(q[element].torque), 1);

        __double_clone_array(&(p[element].torque_cmd), &(q[element].torque_cmd), 1);

        __double_clone_array(&(p[element].iq), &(q[element].iq), 1);

        __double_clone_array(&(p[element].iq_cmd), &(q[element].iq_cmd), 1);

        __double_clone_array(&(p[element].id), &(q[element].id), 1);

        __double_clone_array(&(p[element].vq), &(q[element].vq), 1);

        __double_clone_array(&(p[element].vq_cmd), &(q[element].vq_cmd), 1);

        __double_clone_array(&(p[element].vd), &(q[element].vd), 1);

        __double_clone_array(&(p[element].kp), &(q[element].kp), 1);

        __double_clone_array(&(p[element].kd), &(q[element].kd), 1);

        __int8_t_clone_array(&(p[element].led), &(q[element].led), 1);

        __int8_t_clone_array(&(p[element].cmd_id), &(q[element].cmd_id), 1);

        __int8_t_clone_array(&(p[element].flag), &(q[element].flag), 1);

        __int8_t_clone_array(&(p[element].control_flag), &(q[element].control_flag), 1);

    }
    return 0;
}

FOC_motor_t *FOC_motor_t_copy(const FOC_motor_t *p)
{
    FOC_motor_t *q = (FOC_motor_t*) malloc(sizeof(FOC_motor_t));
    __FOC_motor_t_clone_array(p, q, 1);
    return q;
}

void FOC_motor_t_destroy(FOC_motor_t *p)
{
    __FOC_motor_t_decode_array_cleanup(p, 1);
    free(p);
}

int FOC_motor_t_publish(lcm_t *lc, const char *channel, const FOC_motor_t *p)
{
      int max_data_size = FOC_motor_t_encoded_size (p);
      uint8_t *buf = (uint8_t*) malloc (max_data_size);
      if (!buf) return -1;
      int data_size = FOC_motor_t_encode (buf, 0, max_data_size, p);
      if (data_size < 0) {
          free (buf);
          return data_size;
      }
      int status = lcm_publish (lc, channel, buf, data_size);
      free (buf);
      return status;
}

struct _FOC_motor_t_subscription_t {
    FOC_motor_t_handler_t user_handler;
    void *userdata;
    lcm_subscription_t *lc_h;
};
static
void FOC_motor_t_handler_stub (const lcm_recv_buf_t *rbuf,
                            const char *channel, void *userdata)
{
    int status;
    FOC_motor_t p;
    memset(&p, 0, sizeof(FOC_motor_t));
    status = FOC_motor_t_decode (rbuf->data, 0, rbuf->data_size, &p);
    if (status < 0) {
        fprintf (stderr, "error %d decoding FOC_motor_t!!!\n", status);
        return;
    }

    FOC_motor_t_subscription_t *h = (FOC_motor_t_subscription_t*) userdata;
    h->user_handler (rbuf, channel, &p, h->userdata);

    FOC_motor_t_decode_cleanup (&p);
}

FOC_motor_t_subscription_t* FOC_motor_t_subscribe (lcm_t *lcm,
                    const char *channel,
                    FOC_motor_t_handler_t f, void *userdata)
{
    FOC_motor_t_subscription_t *n = (FOC_motor_t_subscription_t*)
                       malloc(sizeof(FOC_motor_t_subscription_t));
    n->user_handler = f;
    n->userdata = userdata;
    n->lc_h = lcm_subscribe (lcm, channel,
                                 FOC_motor_t_handler_stub, n);
    if (n->lc_h == NULL) {
        fprintf (stderr,"couldn't reg FOC_motor_t LCM handler!\n");
        free (n);
        return NULL;
    }
    return n;
}

int FOC_motor_t_subscription_set_queue_capacity (FOC_motor_t_subscription_t* subs,
                              int num_messages)
{
    return lcm_subscription_set_queue_capacity (subs->lc_h, num_messages);
}

int FOC_motor_t_unsubscribe(lcm_t *lcm, FOC_motor_t_subscription_t* hid)
{
    int status = lcm_unsubscribe (lcm, hid->lc_h);
    if (0 != status) {
        fprintf(stderr,
           "couldn't unsubscribe FOC_motor_t_handler %p!\n", hid);
        return -1;
    }
    free (hid);
    return 0;
}

