// THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
// BY HAND!!
//
// Generated by lcm-gen

#ifndef _mypackage_Position_h
#define _mypackage_Position_h

#include <stdint.h>
#include <stdlib.h>
#include <lcm/lcm_coretypes.h>
#include <lcm/lcm.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef struct _mypackage_Position mypackage_Position;
struct _mypackage_Position
{
    double     x;
    double     y;
};

/**
 * Create a deep copy of a mypackage_Position.
 * When no longer needed, destroy it with mypackage_Position_destroy()
 */
mypackage_Position* mypackage_Position_copy(const mypackage_Position* to_copy);

/**
 * Destroy an instance of mypackage_Position created by mypackage_Position_copy()
 */
void mypackage_Position_destroy(mypackage_Position* to_destroy);

/**
 * Identifies a single subscription.  This is an opaque data type.
 */
typedef struct _mypackage_Position_subscription_t mypackage_Position_subscription_t;

/**
 * Prototype for a callback function invoked when a message of type
 * mypackage_Position is received.
 */
typedef void(*mypackage_Position_handler_t)(
    const lcm_recv_buf_t *rbuf, const char *channel,
    const mypackage_Position *msg, void *userdata);

/**
 * Publish a message of type mypackage_Position using LCM.
 *
 * @param lcm The LCM instance to publish with.
 * @param channel The channel to publish on.
 * @param msg The message to publish.
 * @return 0 on success, <0 on error.  Success means LCM has transferred
 * responsibility of the message data to the OS.
 */
int mypackage_Position_publish(lcm_t *lcm, const char *channel, const mypackage_Position *msg);

/**
 * Subscribe to messages of type mypackage_Position using LCM.
 *
 * @param lcm The LCM instance to subscribe with.
 * @param channel The channel to subscribe to.
 * @param handler The callback function invoked by LCM when a message is
 *     received. This function is invoked by LCM during calls to lcm_handle()
 *     and lcm_handle_timeout().
 * @param userdata An opaque pointer passed to @p handler when it is invoked.
 * @return 0 on success, <0 if an error occured
 */
mypackage_Position_subscription_t* mypackage_Position_subscribe(
    lcm_t *lcm, const char *channel, mypackage_Position_handler_t handler, void *userdata);

/**
 * Removes and destroys a subscription created by mypackage_Position_subscribe()
 */
int mypackage_Position_unsubscribe(lcm_t *lcm, mypackage_Position_subscription_t* hid);

/**
 * Sets the queue capacity for a subscription.
 * Some LCM providers (e.g., the default multicast provider) are implemented
 * using a background receive thread that constantly revceives messages from
 * the network.  As these messages are received, they are buffered on
 * per-subscription queues until dispatched by lcm_handle().  This function
 * how many messages are queued before dropping messages.
 *
 * @param subs the subscription to modify.
 * @param num_messages The maximum number of messages to queue
 *  on the subscription.
 * @return 0 on success, <0 if an error occured
 */
int mypackage_Position_subscription_set_queue_capacity(
    mypackage_Position_subscription_t* subs, int num_messages);

/**
 * Encode a message of type mypackage_Position into binary form.
 *
 * @param buf The output buffer.
 * @param offset Encoding starts at this byte offset into @p buf.
 * @param maxlen Maximum number of bytes to write.  This should generally
 *               be equal to mypackage_Position_encoded_size().
 * @param msg The message to encode.
 * @return The number of bytes encoded, or <0 if an error occured.
 */
int mypackage_Position_encode(void *buf, int offset, int maxlen, const mypackage_Position *p);

/**
 * Decode a message of type mypackage_Position from binary form.
 * When decoding messages containing strings or variable-length arrays, this
 * function may allocate memory.  When finished with the decoded message,
 * release allocated resources with mypackage_Position_decode_cleanup().
 *
 * @param buf The buffer containing the encoded message
 * @param offset The byte offset into @p buf where the encoded message starts.
 * @param maxlen The maximum number of bytes to read while decoding.
 * @param msg Output parameter where the decoded message is stored
 * @return The number of bytes decoded, or <0 if an error occured.
 */
int mypackage_Position_decode(const void *buf, int offset, int maxlen, mypackage_Position *msg);

/**
 * Release resources allocated by mypackage_Position_decode()
 * @return 0
 */
int mypackage_Position_decode_cleanup(mypackage_Position *p);

/**
 * Check how many bytes are required to encode a message of type mypackage_Position
 */
int mypackage_Position_encoded_size(const mypackage_Position *p);

// LCM support functions. Users should not call these
int64_t __mypackage_Position_get_hash(void);
uint64_t __mypackage_Position_hash_recursive(const __lcm_hash_ptr *p);
int __mypackage_Position_encode_array(
    void *buf, int offset, int maxlen, const mypackage_Position *p, int elements);
int __mypackage_Position_decode_array(
    const void *buf, int offset, int maxlen, mypackage_Position *p, int elements);
int __mypackage_Position_decode_array_cleanup(mypackage_Position *p, int elements);
int __mypackage_Position_encoded_array_size(const mypackage_Position *p, int elements);
int __mypackage_Position_clone_array(const mypackage_Position *p, mypackage_Position *q, int elements);

#ifdef __cplusplus
}
#endif

#endif
