// THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
// BY HAND!!
//
// Generated by lcm-gen

#include <string.h>
#include "mypackage_Position.h"

static int __mypackage_Position_hash_computed;
static uint64_t __mypackage_Position_hash;

uint64_t __mypackage_Position_hash_recursive(const __lcm_hash_ptr *p)
{
    const __lcm_hash_ptr *fp;
    for (fp = p; fp != NULL; fp = fp->parent)
        if (fp->v == __mypackage_Position_get_hash)
            return 0;

    __lcm_hash_ptr cp;
    cp.parent =  p;
    cp.v = __mypackage_Position_get_hash;
    (void) cp;

    uint64_t hash = (uint64_t)0xd259512e30b44885LL
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
        ;

    return (hash<<1) + ((hash>>63)&1);
}

int64_t __mypackage_Position_get_hash(void)
{
    if (!__mypackage_Position_hash_computed) {
        __mypackage_Position_hash = (int64_t)__mypackage_Position_hash_recursive(NULL);
        __mypackage_Position_hash_computed = 1;
    }

    return __mypackage_Position_hash;
}

int __mypackage_Position_encode_array(void *buf, int offset, int maxlen, const mypackage_Position *p, int elements)
{
    int pos = 0, element;
    int thislen;

    for (element = 0; element < elements; element++) {

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &(p[element].x), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &(p[element].y), 1);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int mypackage_Position_encode(void *buf, int offset, int maxlen, const mypackage_Position *p)
{
    int pos = 0, thislen;
    int64_t hash = __mypackage_Position_get_hash();

    thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    thislen = __mypackage_Position_encode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int __mypackage_Position_encoded_array_size(const mypackage_Position *p, int elements)
{
    int size = 0, element;
    for (element = 0; element < elements; element++) {

        size += __double_encoded_array_size(&(p[element].x), 1);

        size += __double_encoded_array_size(&(p[element].y), 1);

    }
    return size;
}

int mypackage_Position_encoded_size(const mypackage_Position *p)
{
    return 8 + __mypackage_Position_encoded_array_size(p, 1);
}

int __mypackage_Position_decode_array(const void *buf, int offset, int maxlen, mypackage_Position *p, int elements)
{
    int pos = 0, thislen, element;

    for (element = 0; element < elements; element++) {

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &(p[element].x), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &(p[element].y), 1);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int __mypackage_Position_decode_array_cleanup(mypackage_Position *p, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __double_decode_array_cleanup(&(p[element].x), 1);

        __double_decode_array_cleanup(&(p[element].y), 1);

    }
    return 0;
}

int mypackage_Position_decode(const void *buf, int offset, int maxlen, mypackage_Position *p)
{
    int pos = 0, thislen;
    int64_t hash = __mypackage_Position_get_hash();

    int64_t this_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (this_hash != hash) return -1;

    thislen = __mypackage_Position_decode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int mypackage_Position_decode_cleanup(mypackage_Position *p)
{
    return __mypackage_Position_decode_array_cleanup(p, 1);
}

int __mypackage_Position_clone_array(const mypackage_Position *p, mypackage_Position *q, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __double_clone_array(&(p[element].x), &(q[element].x), 1);

        __double_clone_array(&(p[element].y), &(q[element].y), 1);

    }
    return 0;
}

mypackage_Position *mypackage_Position_copy(const mypackage_Position *p)
{
    mypackage_Position *q = (mypackage_Position*) malloc(sizeof(mypackage_Position));
    __mypackage_Position_clone_array(p, q, 1);
    return q;
}

void mypackage_Position_destroy(mypackage_Position *p)
{
    __mypackage_Position_decode_array_cleanup(p, 1);
    free(p);
}

int mypackage_Position_publish(lcm_t *lc, const char *channel, const mypackage_Position *p)
{
      int max_data_size = mypackage_Position_encoded_size (p);
      uint8_t *buf = (uint8_t*) malloc (max_data_size);
      if (!buf) return -1;
      int data_size = mypackage_Position_encode (buf, 0, max_data_size, p);
      if (data_size < 0) {
          free (buf);
          return data_size;
      }
      int status = lcm_publish (lc, channel, buf, data_size);
      free (buf);
      return status;
}

struct _mypackage_Position_subscription_t {
    mypackage_Position_handler_t user_handler;
    void *userdata;
    lcm_subscription_t *lc_h;
};
static
void mypackage_Position_handler_stub (const lcm_recv_buf_t *rbuf,
                            const char *channel, void *userdata)
{
    int status;
    mypackage_Position p;
    memset(&p, 0, sizeof(mypackage_Position));
    status = mypackage_Position_decode (rbuf->data, 0, rbuf->data_size, &p);
    if (status < 0) {
        fprintf (stderr, "error %d decoding mypackage_Position!!!\n", status);
        return;
    }

    mypackage_Position_subscription_t *h = (mypackage_Position_subscription_t*) userdata;
    h->user_handler (rbuf, channel, &p, h->userdata);

    mypackage_Position_decode_cleanup (&p);
}

mypackage_Position_subscription_t* mypackage_Position_subscribe (lcm_t *lcm,
                    const char *channel,
                    mypackage_Position_handler_t f, void *userdata)
{
    mypackage_Position_subscription_t *n = (mypackage_Position_subscription_t*)
                       malloc(sizeof(mypackage_Position_subscription_t));
    n->user_handler = f;
    n->userdata = userdata;
    n->lc_h = lcm_subscribe (lcm, channel,
                                 mypackage_Position_handler_stub, n);
    if (n->lc_h == NULL) {
        fprintf (stderr,"couldn't reg mypackage_Position LCM handler!\n");
        free (n);
        return NULL;
    }
    return n;
}

int mypackage_Position_subscription_set_queue_capacity (mypackage_Position_subscription_t* subs,
                              int num_messages)
{
    return lcm_subscription_set_queue_capacity (subs->lc_h, num_messages);
}

int mypackage_Position_unsubscribe(lcm_t *lcm, mypackage_Position_subscription_t* hid)
{
    int status = lcm_unsubscribe (lcm, hid->lc_h);
    if (0 != status) {
        fprintf(stderr,
           "couldn't unsubscribe mypackage_Position_handler %p!\n", hid);
        return -1;
    }
    free (hid);
    return 0;
}

