/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package mypackage;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class Position implements lcm.lcm.LCMEncodable
{
    public double x;
    public double y;
 
    public Position()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0xd259512e30b44885L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(mypackage.Position.class))
            return 0L;
 
        classes.add(mypackage.Position.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeDouble(this.x); 
 
        outs.writeDouble(this.y); 
 
    }
 
    public Position(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public Position(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static mypackage.Position _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        mypackage.Position o = new mypackage.Position();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.x = ins.readDouble();
 
        this.y = ins.readDouble();
 
    }
 
    public mypackage.Position copy()
    {
        mypackage.Position outobj = new mypackage.Position();
        outobj.x = this.x;
 
        outobj.y = this.y;
 
        return outobj;
    }
 
}

