/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package FOC;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class motor_t implements lcm.lcm.LCMEncodable
{
    public double position;
    public double position_cmd;
    public double velocity;
    public double velocity_cmd;
    public double torque;
    public double torque_cmd;
    public double iq;
    public double iq_cmd;
    public double id;
    public double vq;
    public double vq_cmd;
    public double vd;
    public double kp;
    public double kd;
    public byte led;
    public byte cmd_id;
    public byte flag;
    public byte control_flag;
 
    public motor_t()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0xda042e0da5c652d5L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(FOC.motor_t.class))
            return 0L;
 
        classes.add(FOC.motor_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeDouble(this.position); 
 
        outs.writeDouble(this.position_cmd); 
 
        outs.writeDouble(this.velocity); 
 
        outs.writeDouble(this.velocity_cmd); 
 
        outs.writeDouble(this.torque); 
 
        outs.writeDouble(this.torque_cmd); 
 
        outs.writeDouble(this.iq); 
 
        outs.writeDouble(this.iq_cmd); 
 
        outs.writeDouble(this.id); 
 
        outs.writeDouble(this.vq); 
 
        outs.writeDouble(this.vq_cmd); 
 
        outs.writeDouble(this.vd); 
 
        outs.writeDouble(this.kp); 
 
        outs.writeDouble(this.kd); 
 
        outs.writeByte(this.led); 
 
        outs.writeByte(this.cmd_id); 
 
        outs.writeByte(this.flag); 
 
        outs.writeByte(this.control_flag); 
 
    }
 
    public motor_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public motor_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static FOC.motor_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        FOC.motor_t o = new FOC.motor_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.position = ins.readDouble();
 
        this.position_cmd = ins.readDouble();
 
        this.velocity = ins.readDouble();
 
        this.velocity_cmd = ins.readDouble();
 
        this.torque = ins.readDouble();
 
        this.torque_cmd = ins.readDouble();
 
        this.iq = ins.readDouble();
 
        this.iq_cmd = ins.readDouble();
 
        this.id = ins.readDouble();
 
        this.vq = ins.readDouble();
 
        this.vq_cmd = ins.readDouble();
 
        this.vd = ins.readDouble();
 
        this.kp = ins.readDouble();
 
        this.kd = ins.readDouble();
 
        this.led = ins.readByte();
 
        this.cmd_id = ins.readByte();
 
        this.flag = ins.readByte();
 
        this.control_flag = ins.readByte();
 
    }
 
    public FOC.motor_t copy()
    {
        FOC.motor_t outobj = new FOC.motor_t();
        outobj.position = this.position;
 
        outobj.position_cmd = this.position_cmd;
 
        outobj.velocity = this.velocity;
 
        outobj.velocity_cmd = this.velocity_cmd;
 
        outobj.torque = this.torque;
 
        outobj.torque_cmd = this.torque_cmd;
 
        outobj.iq = this.iq;
 
        outobj.iq_cmd = this.iq_cmd;
 
        outobj.id = this.id;
 
        outobj.vq = this.vq;
 
        outobj.vq_cmd = this.vq_cmd;
 
        outobj.vd = this.vd;
 
        outobj.kp = this.kp;
 
        outobj.kd = this.kd;
 
        outobj.led = this.led;
 
        outobj.cmd_id = this.cmd_id;
 
        outobj.flag = this.flag;
 
        outobj.control_flag = this.control_flag;
 
        return outobj;
    }
 
}

